using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeAutomation.Base.Enums;

public enum ZWaveEventParameter
{
    Basic = 0,
    SwitchBinary = 1,
    SwitchMultilevel = 2,
    ManufacturerSpecific = 3,
    MeterKwHour = 4,
    MeterKvaHour = 5,
    MeterWatt = 6,
    MeterPulses = 7,
    MeterAcVolt = 8,
    MeterAcCurrent = 9,
    MeterPower = 10,
    SensorGeneric = 11,
    SensorTemperature = 12,
    SensorHumidity = 13,
    SensorLuminance = 14,
    SensorMotion = 15,
    AlarmGeneric = 16,
    AlarmDoorWindow = 17,
    AlarmSmoke = 18,
    AlarmCarbonMonoxide = 19,
    AlarmCarbonDioxide = 20,
    AlarmHeat = 21,
    AlarmFlood = 22,
    AlarmTampered = 23,
    Configuration = 24,
    WakeUpInterval = 25,
    WakeUpNotify = 26,
    WakeUpSleepingStatus = 27,
    Association = 28,
    VersionCommandClass = 29,
    Battery = 30,
    NodeInfo = 31,
    MultiinstanceSwitchBinaryCount = 32,
    MultiinstanceSwitchBinary = 33,
    MultiinstanceSwitchMultilevelCount = 34,
    MultiinstanceSwitchMultilevel = 35,
    MultiinstanceSensorBinaryCount = 36,
    MultiinstanceSensorBinary = 37,
    MultiinstanceSensorMultilevelCount = 38,
    MultiinstanceSensorMultilevel = 39,
    ThermostatFanMode = 40,
    ThermostatFanState = 41,
    ThermostatHeating = 42,
    ThermostatMode = 43,
    ThermostatOperatingState = 44,
    ThermostatSetBack = 45,
    ThermostatSetPoint = 46,
    UserCode = 47,
    SecurityNodeInformationFrame = 48,
    SecurityDecriptedMessage = 49,
    SecurityGeneratedKey = 50,
    DoorLockStatus = 51,
    RoutingInfo = 52,
    Clock = 53,
    CentralSceneNotification = 54,
    CentralSceneSupportedReport = 55,
    IrrigationSystemInfoReport = 56,
    IrrigationSystemStatusReport = 57,
    IrrigationSystemConfigReport = 58,
    IrrigationValveInfoReport = 59,
    IrrigationValveConfigReport = 60,
    IrrigationValveTableReport = 61,
    WaterFlow = 62,
    WaterPressure = 63,
    ClimateControlSchedule = 64,
    ClimateControlScheduleChanged = 65,
    ClimateControlScheduleOverride = 66,
    Ultraviolet = 67,
    CapabilityReport = 68
}
